### ISSUE TITLE
Followed install directions for inpainting model but app crashes

### ISSUE THREAD

**Issue by agret** [JbPasquier/stable-diffusion-onnx-ui#5]
(venv) R:\Development\stable-diffusion-amd>python --version
Python 3.10.7

Prompt used "a man standing by a lake"

With AMD GPU:

` Running on local URL:  http://0.0.0.0:7860
2023-02-28 16:39:24.3514413 [W:onnxruntime:, inference_session.cc:497 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2023-02-28 16:39:24.7703026 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-02-28 16:39:24.7774236 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-02-28 16:39:26.0514947 [W:onnxruntime:, inference_session.cc:497 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2023-02-28 16:39:26.1323468 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-02-28 16:39:26.1375511 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-02-28 16:39:26.5632144 [W:onnxruntime:, inference_session.cc:497 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2023-02-28 16:39:28.3066281 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-02-28 16:39:28.3127331 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
2023-02-28 16:39:33.4451536 [W:onnxruntime:, inference_session.cc:497 onnxruntime::InferenceSession::RegisterExecutionProvider] Having memory pattern enabled is not supported while using the DML Execution Provider. So disabling it for this session since it uses the DML Execution Provider.
2023-02-28 16:39:33.5465176 [W:onnxruntime:, session_state.cc:1136 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Some nodes were not assigned to the preferred execution providers which may or may not have an negative impact on performance. e.g. ORT explicitly assigns shape related ops to CPU to improve perf.
2023-02-28 16:39:33.5549729 [W:onnxruntime:, session_state.cc:1138 onnxruntime::VerifyEachNodeIsAssignedToAnEp] Rerunning with verbose output on a non-minimal build will show node assignments.
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]2023-02-28 16:39:34.0990167 [E:onnxruntime:, sequential_executor.cc:494 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/conv_in/Conv' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2340)\onnxruntime_pybind11_state.pyd!00007FFCD61FEEA5: (caller: 00007FFCD6200022) Exception(3) tid(eb64) 80070057 The parameter is incorrect.

  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "R:\Development\stable-diffusion-amd\app.py", line 177, in generate_click
    return run_diffusers(
  File "R:\Development\stable-diffusion-amd\app.py", line 92, in run_diffusers
    batch_images = pipe(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 273, in __call__
    noise_pred = self.unet(sample=latent_model_input, timestep=timestep, encoder_hidden_states=prompt_embeds)
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\diffusers\pipelines\onnx_utils.py", line 60, in __call__
    return self.model.run(None, inputs)
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Conv node. Name:'/conv_in/Conv' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\dml\DmlExecutionProvider\src\MLOperatorAuthorImpl.cpp(2340)\onnxruntime_pybind11_state.pyd!00007FFCD61FEEA5: (caller: 00007FFCD6200022) Exception(3) tid(eb64) 80070057 The parameter is incorrect. `

With CPU only:

`(venv) R:\Development\stable-diffusion-amd>python app.py --local --cpu-only
Running on local URL:  http://0.0.0.0:7860
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]2023-02-28 16:41:33.1500161 [E:onnxruntime:, sequential_executor.cc:494 onnxruntime::ExecuteKernel] Non-zero status code returned while running Conv node. Name:'/conv_in/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 4 kernel channels: 9 group: 1
  0%|                                                                                           | 0/25 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\blocks.py", line 1024, in process_api
    result = await self.call_function(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\gradio\blocks.py", line 836, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "R:\Development\stable-diffusion-amd\app.py", line 177, in generate_click
    return run_diffusers(
  File "R:\Development\stable-diffusion-amd\app.py", line 92, in run_diffusers
    batch_images = pipe(
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\diffusers\pipelines\stable_diffusion\pipeline_onnx_stable_diffusion.py", line 273, in __call__
    noise_pred = self.unet(sample=latent_model_input, timestep=timestep, encoder_hidden_states=prompt_embeds)
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\diffusers\pipelines\onnx_utils.py", line 60, in __call__
    return self.model.run(None, inputs)
  File "R:\Development\stable-diffusion-amd\venv\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Non-zero status code returned while running Conv node. Name:'/conv_in/Conv' Status Message: Input channels C is not equal to kernel channels * group. C: 4 kernel channels: 9 group: 1`

**Comment by JbPasquier** [comment]
I hadn't updated this repository for a while.

I'll have a look whenever I'll be able to. No ETA, sorry.
